### ISSUE TITLE
Fix app install metric

### ISSUE THREAD

**Issue by bsmith42** [eyefi/waffle-ios#13]
The rate seems very high...

**Comment by berendo** [comment]
I'm pretty much completely unfamiliar with how it was done via Apps Flyer, but I'll take a look...

¯\_(ツ)_/¯

**Comment by berendo** [comment]
The Apps Flyer stuff is here:

https://github.eye.fi/eyefi/ios/blob/master/MysteryHouse/Disneyland/AppDelegate.m#L1216-1239

 I wonder if `onConversionReceived` is firing on every single app launch, in which case every install would get reported as many times as the app is launched subsequently.

**Comment by bsmith42** [comment]
The funny thing is that the number of app installs is quite a bit higher
than the reported app launch events.

**Comment by bsmith42** [comment]
Just checked, peak app launches 10k, peak app installs 40k

**Comment by berendo** [comment]
From the AppsFlyer integration guide at https://support.appsflyer.com/entries/25458906-iOS-SDK-Integration-Guide-v2-5-3-x-New-API-

![image](https://cloud.githubusercontent.com/assets/1772903/7459421/ad6aff96-f250-11e4-9618-1aa5db4d34d5.png)

It looks like we are supposed to call `[[AppsFlyerTracker sharedTracker] trackAppLaunch]` from within `applicationDidBecomeActive` (which gets fired on both initial launches of the app, as well as re-foregrounding), so I'm not sure if there's anything else to do in the app.

**Comment by berendo** [comment]
@bsmith42 taking a step back, when you say "app install metric," are you referring to AppsFlyer data or Mixpanel data?

**Comment by berendo** [comment]
OK. Assuming you were reporting an issue with the latter (i.e. Mixpanel), I've definitely spotted that Radhika never put in any logic to report install events only once. It should be fixed in [eyefi/ios@`07aa97f`](https://github.eye.fi/eyefi/ios/commit/07aa97f26098da10bba5a750a2dfd3bfe8bbfce8).

**Comment by bsmith42** [comment]
Only mixpanel reports.

**Comment by berendo** [comment]
:+1: , then. I added persistence on top of Radhika's work to "remember" if we've already reported the "app install" event to the Mixpanel side of the world.
